version: '3.8'

services:
  app:
    image: app:v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mss_blog?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
    networks:
        - myapp_network
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: mss_blog
#      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    networks:
      - myapp_network
    expose:
      - "3306:3306"
    restart: unless-stopped

networks:
  myapp_network:
    driver: bridge
